export const data = [
  {
    img: "/image/canon.jpg",
    cat: `/products/camera`,
    desc: "Check out new models!",
    name: "Camera",
    id: 0,
  },
  {
    img: "/image/mac.jpg",
    cat: `/products/laptop`,
    desc: "Discounts up to 20% for Laptops",
    name: "Laptop",
    id: 1,
  },
  {
    img: "/image/iphone.jpg",
    cat: "/products/phone",
    desc: "Special Discount!",
    name: "Phone",
    id: 2,
  },
  {
    img: "/image/tablet.jpg",
    cat: "/products/tablet",
    desc: "tablet",
    name: "Tablet",
    id: 3,
  },
  {
    img: "/image/television.jpg",
    cat: "/products/television",
    desc: "Check out our new models!",
    name: "Television",
    id: 4,
  },
  {
    img: "/image/watch.jpg",
    cat: "/products/watch",
    desc: "watch",
    name: "Watch",
    id: 5,
  },
];

export const products = [
  {
    title: "MacBook Pro",
    img: "https://cdn.vatanbilgisayar.com/Upload/PRODUCT/apple/thumb/114762_large.jpg",
    desc: "Backlit Magic Keyboard, Touch Bar, Touch ID, and Force Touch trackpad.",
    price: 499,
  },
  {
    title: "Apple Watch",
    img: "https://productimages.hepsiburada.net/s/140/300-443/110000093110255.jpg",
    desc: "High and low heart rate notifications Irregular heart rhythm notification",
    price: 99,
  },
  {
    title: "IPad Pro",
    img: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/ipad-pro-12-select-wifi-spacegray-202104_GEO_TR_FMT_WHH?wid=940&hei=1112&fmt=p-jpg&qlt=95&.v=1617923582000",
    desc: "12MP back camera with Focus Pixels and 7MP FaceTime HD camera with improved low-light performance.",
    price: 129,
  },
  {
    title: "IPhone 12 Pro",
    img: "https://cdn.dsmcdn.com/ty37/product/media/images/20201222/17/40863459/113604745/1/1_org_zoom.jpg",
    desc: "5G goes Pro. A14 Bionic rockets past every other smartphone chip. The Pro camera system takes low-light photography to the next level — with an even bigger jump on iPhone 12 Pro Max.",
    price: 199,
  },
  {
    title: "Canon Camera",
    img: "https://m.media-amazon.com/images/I/41Xn25rH9xL._AC_SY580_.jpg",
    desc: "Characterized by versatile imaging specs, the Canon EOS 80D further clarifies itself using a pair of robust focusing systems and an intuitive design",
    price: 249,
  },
  {
    title: "Samsung Smart TV",
    img: "https://cdn.cimri.io/image/1000x1000/samsungninchsmartwififullhdledtv_110669142.jpg",
    desc: "Turn the ordinary into the extraordinary with immersive sound, endless detail, minimalist design and unrivaled technology.",
    price: 129,
  },
  {
    title: "Samsung Smart TV",
    img: "https://cdn.cimri.io/image/1000x1000/samsungninchsmartwififullhdledtv_110669142.jpg",
    desc: "Turn the ordinary into the extraordinary with immersive sound, endless detail, minimalist design and unrivaled technology.",
    price: 129,
  },
  {
    title: "Samsung Smart TV",
    img: "https://cdn.cimri.io/image/1000x1000/samsungninchsmartwififullhdledtv_110669142.jpg",
    desc: "Turn the ordinary into the extraordinary with immersive sound, endless detail, minimalist design and unrivaled technology.",
    price: 129,
  },
  {
    title: "Samsung Smart TV",
    img: "https://cdn.cimri.io/image/1000x1000/samsungninchsmartwififullhdledtv_110669142.jpg",
    desc: "Turn the ordinary into the extraordinary with immersive sound, endless detail, minimalist design and unrivaled technology.",
    price: 129,
  },
  {
    title: "Samsung Smart TV",
    img: "https://cdn.cimri.io/image/1000x1000/samsungninchsmartwififullhdledtv_110669142.jpg",
    desc: "Turn the ordinary into the extraordinary with immersive sound, endless detail, minimalist design and unrivaled technology.",
    price: 129,
  },
  {
    title: "Samsung Smart TV",
    img: "https://cdn.cimri.io/image/1000x1000/samsungninchsmartwififullhdledtv_110669142.jpg",
    desc: "Turn the ordinary into the extraordinary with immersive sound, endless detail, minimalist design and unrivaled technology.",
    price: 129,
  },
  {
    title: "Samsung Smart TV",
    img: "https://cdn.cimri.io/image/1000x1000/samsungninchsmartwififullhdledtv_110669142.jpg",
    desc: "Turn the ordinary into the extraordinary with immersive sound, endless detail, minimalist design and unrivaled technology.",
    price: 129,
  },
  {
    title: "Samsung Smart TV",
    img: "https://cdn.cimri.io/image/1000x1000/samsungninchsmartwififullhdledtv_110669142.jpg",
    desc: "Turn the ordinary into the extraordinary with immersive sound, endless detail, minimalist design and unrivaled technology.",
    price: 129,
  },
  {
    title: "Samsung Smart TV",
    img: "https://cdn.cimri.io/image/1000x1000/samsungninchsmartwififullhdledtv_110669142.jpg",
    desc: "Turn the ordinary into the extraordinary with immersive sound, endless detail, minimalist design and unrivaled technology.",
    price: 129,
  },
];

export const userRows = [
  {
    id: 1,
    username: "Snow",
    email: "Jon@gmail.com",
    status: "active",
    transaction: "$150.00",
  },
  {
    id: 2,
    username: "Snow",
    email: "Jon@gmail.com",
    status: "active",
    transaction: "$150.00",
  },
  {
    id: 3,
    username: "Snow",
    email: "Jon@gmail.com",
    status: "active",
    transaction: "$150.00",
  },
  {
    id: 4,
    username: "Snow",
    email: "Jon@gmail.com",
    status: "active",
    transaction: "$150.00",
  },
  {
    id: 5,
    username: "Snow",
    email: "Jon@gmail.com",
    status: "active",
    transaction: "$150.00",
  },
  {
    id: 6,
    username: "Snow",
    email: "Jon@gmail.com",
    status: "active",
    transaction: "$150.00",
  },
  {
    id: 7,
    username: "Snow",
    email: "Jon@gmail.com",
    status: "active",
    transaction: "$150.00",
  },
  {
    id: 8,
    username: "Snow",
    email: "Jon@gmail.com",
    status: "active",
    transaction: "$150.00",
  },
  {
    id: 9,
    username: "Snow",
    email: "Jon@gmail.com",
    status: "active",
    transaction: "$150.00",
  },
];

export const productRows = [
  {
    id: 1,
    stock: "222",
    status: "active",
    price: "$150",
    name: "Iphone",
    img: "https://cdn.dsmcdn.com/ty37/product/media/images/20201222/17/40863459/113604745/1/1_org_zoom.jpg",
  },
  {
    id: 2,
    stock: "222",
    status: "active",
    price: "$150",
    name: "Iphone",
    img: "https://cdn.dsmcdn.com/ty37/product/media/images/20201222/17/40863459/113604745/1/1_org_zoom.jpg",
  },
  {
    id: 3,
    stock: "222",
    status: "active",
    price: "$150",
    name: "Iphone",
    img: "https://cdn.dsmcdn.com/ty37/product/media/images/20201222/17/40863459/113604745/1/1_org_zoom.jpg",
  },
  {
    id: 4,
    stock: "222",
    status: "active",
    price: "$150",
    name: "Iphone",
    img: "https://cdn.dsmcdn.com/ty37/product/media/images/20201222/17/40863459/113604745/1/1_org_zoom.jpg",
  },
  {
    id: 5,
    stock: "222",
    status: "active",
    price: "$150",
    name: "Iphone",
    img: "https://cdn.dsmcdn.com/ty37/product/media/images/20201222/17/40863459/113604745/1/1_org_zoom.jpg",
  },
  {
    id: 6,
    stock: "222",
    status: "active",
    price: "$150",
    name: "Iphone",
    img: "https://cdn.dsmcdn.com/ty37/product/media/images/20201222/17/40863459/113604745/1/1_org_zoom.jpg",
  },
  {
    id: 7,
    stock: "222",
    status: "active",
    price: "$150",
    name: "Iphone",
    img: "https://cdn.dsmcdn.com/ty37/product/media/images/20201222/17/40863459/113604745/1/1_org_zoom.jpg",
  },
  {
    id: 8,
    stock: "222",
    status: "active",
    price: "$150",
    name: "Iphone",
    img: "https://cdn.dsmcdn.com/ty37/product/media/images/20201222/17/40863459/113604745/1/1_org_zoom.jpg",
  },
  {
    id: 9,
    stock: "222",
    status: "active",
    price: "$150",
    name: "Iphone",
    img: "https://cdn.dsmcdn.com/ty37/product/media/images/20201222/17/40863459/113604745/1/1_org_zoom.jpg",
  },
];

export const chartData = [
  {
    name: "Page A",
    "Active Users": 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "Page B",
    "Active Users": 3000,
    pv: 1398,
    amt: 2210,
  },
  {
    name: "Page C",
    "Active Users": 2000,
    pv: 9800,
    amt: 2290,
  },
  {
    name: "Page D",
    "Active Users": 2780,
    pv: 3908,
    amt: 2000,
  },
  {
    name: "Page E",
    "Active Users": 1890,
    pv: 4800,
    amt: 2181,
  },
  {
    name: "Page F",
    "Active Users": 2390,
    pv: 3800,
    amt: 2500,
  },
  {
    name: "Page G",
    "Active Users": 3490,
    pv: 4300,
    amt: 2100,
  },
];

export const productData = [
  {
    name: "Jan",
    Sales: 4000,
  },
  {
    name: "Feb",
    Sales: 2000,
  },
  {
    name: "Mar",
    Sales: 5000,
  },
];
